package idv.chatea.gldemo.firework;

import android.content.Context;
import android.opengl.GLSurfaceView;
import android.util.AttributeSet;
import android.view.MotionEvent;

/**
 * Created by chatea on 2016/2/2.
 * @author Charlie Tsai (chatea)
 */
public class GLFireworkSurfaceView extends GLSurfaceView {

    /**
     * The minimum frequency of firework generated by single tap.
     * The Unit is milliseconds.
     */
    private static final long MINIMUM_INTERVAL_OF_FIREWORK_GENERATION = 50;
    private long mLastTapTimestamp;

    private GLFireworkRenderer mRenderer;

    public GLFireworkSurfaceView(Context context) {
        super(context);
        init(context);
    }

    public GLFireworkSurfaceView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }

    private void init(Context context) {
        mRenderer = new GLFireworkRenderer(context);

        setEGLContextClientVersion(2);
        setRenderer(mRenderer);
        setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);
    }

    public void handleShakeEvent(float speed) {
        mRenderer.onDeviceShake(speed);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {

        if (event.getPointerCount() > 2) {
            // We don't handle the input event more than 2 points.
            return true;
        }

        if (event.getPointerCount() == 2) {
            if (System.currentTimeMillis() - mLastTapTimestamp > MINIMUM_INTERVAL_OF_FIREWORK_GENERATION) {
                float x = (event.getX(0) + event.getX(1)) / 2f;
                float y = (event.getY(0) + event.getY(1)) / 2f;
                mRenderer.onDoubleTouched(event.getX(0), event.getY(0), event.getX(1), event.getY(1));
                mLastTapTimestamp = System.currentTimeMillis();
            }
            return true;
        }

        // this is not double tap gesture, check single tap case.
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
            case MotionEvent.ACTION_MOVE:
                if (System.currentTimeMillis() - mLastTapTimestamp > MINIMUM_INTERVAL_OF_FIREWORK_GENERATION) {
                    float x = event.getX();
                    float y = event.getY();
                    mRenderer.onScreenTouched(x, y);
                    mLastTapTimestamp = System.currentTimeMillis();
                }
                return true;
            default:
                return super.onTouchEvent(event);
        }
    }
}
